version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: 
          name: Docker build
          command: make build-docker
workflows:
  version: 2
  build:
    jobs:
      - build
