---
version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Docker build
          command: make build-docker

  yetus:
    docker:
      - image: apache/yetus:master
    steps:
      - checkout
      - run:
          name: yetus
          command: >
            test-patch
            --build-tool=nobuild
            --plugins=all,-shelldocs,-gitlab
            --patch-dir=/tmp/yetus-out
            --html-report-file=/tmp/yetus-out/report.html
            --console-report-file=/tmp/yetus-out/console.txt
            --brief-report-file=/tmp/yetus-out/brief.txt
            --excludes=.yetus-excludes
            --line-comments=''
            --bugcomments=briefreport,htmlout
            --empty-patch || true
      - store_artifacts:
          path: /tmp/yetus-out
workflows:
  version: 2
  build:
    jobs:
      - build
      - yetus
